apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ujh906npz-go 
  janus-idp.io/tekton: ujh906npz-go
  backstage.io/kubernetes-id: ujh906npz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ujh906npz-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  